name:                templog-server
version:             0.1.0.0
github:              "forestphoenix/templog-server"
license:             BSD3
author:              "Lars Hollenbach"
maintainer:          "forestphoenix@mailbox.org"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/forestphoenix/templog-server#readme>

dependencies:
- name: base
  version: ">= 4.7 && < 5"qqq
  mixin:
    - hiding (Prelude)
- name: relude
  version: "== 1.2.*"
  mixin:
    - (Relude as Prelude)
- scotty == 0.20.* # TODO: Remove
- blaze-html == 0.9.*
- aeson == 2.1.*
- time
- text

library:
  source-dirs: src

executables:
  templog-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - templog-server
    #TODO: Move scotty here.

tests:
  templog-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - templog-server
