name:                templog-server
version:             0.1.0.0
github:              "forestphoenix/templog-server"
license:             BSD3
author:              "Lars Hollenbach"
maintainer:          "forestphoenix@mailbox.org"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/forestphoenix/templog-server#readme>

dependencies:
- base >= 4.7 && < 5
- relude== 1.2.*
- aeson == 2.1.*
- blaze-html == 0.9.*
- HDBC
- HDBC-session
- HDBC-sqlite3
- persistable-record
- relational-query
- relational-query-HDBC
- relational-record
- scotty == 0.20.*
- template-haskell
- text
- time
- wai

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src

executables:
  templog-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - templog-server

tests:
  templog-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - templog-server
